# Generated by Django 2.1.2 on 2018-11-14 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20181114_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.AddField(
            model_name='department',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
